[package]
name = "infra"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
application.workspace = true
async-trait.workspace = true
domain = { path = "../domain" }
firestore-client = { path = "../firestore-client" }
serde.workspace = true
tokio.workspace = true
