[package]
name = "infra"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
application.workspace = true
async-trait.workspace = true
domain.workspace = true
firestore-client.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
