[package]
name = "application"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
domain.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
anyhow.workspace = true
