services:
  firebase:
    build: ./firebase
    volumes:
      - ./firebase:/firebase

  workspace:
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase:8080
    image: debian:trixie
    volumes:
      - .:/workspaces/tsukota-web:cached
      - ~/.claude:/home/vscode/.claude
      - ~/.copilot:/home/vscode/.copilot
