[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["bouzuya"]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "1.0.0"

[workspace.dependencies]
anyhow = "1"
bouzuya-firestore-client = { git = "https://github.com/bouzuya/bouzuya-firestore-client", tag = "3.2.0" }
api = { path = "crates/api" }
application = { path = "crates/application" }
async-trait = "0.1"
date-time = { path = "crates/date-time" }
domain = { path = "crates/domain" }
infra = { path = "crates/infra" }
mockall = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serial_test = "3"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4"] }
