[package]
name = "firestore-client"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
firestore-path = "1"
http = "1"
google-cloud-auth = "1.4.0"
googleapis-tonic-google-firestore-v1 = "0.27"
serde.workspace = true
serde-firestore-value = "0.24.3"
thiserror.workspace = true
tonic = { version = "0.14.2", features = ["tls-webpki-roots"] }

[dev-dependencies]
anyhow.workspace = true
tokio.workspace = true
uuid.workspace = true
