[package]
name = "api"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
application.workspace = true
axum = "0.8"
axum-extra = { version = "0.10", features = ["cookie", "cookie-signed"] }
cookie = { version = "0.18", features = ["percent-encode"] }
domain.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http = { version = "0.6", features = ["fs", "trace"] }
tracing.workspace = true

[dev-dependencies]
anyhow.workspace = true
