[package]
name = "main"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "tsukota-server"
path = "src/main.rs"

[dev-dependencies]
anyhow.workspace = true
temp-env = "0.3"

[dependencies]
api.workspace = true
application.workspace = true
bouzuya-firestore-client.workspace = true
clap = { version = "4", features = ["derive"] }
date-time.workspace = true
domain.workspace = true
hex = "0.4"
infra.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
