[package]
name = "main"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "tsukota-server"
path = "src/main.rs"

[dependencies]
api = { path = "../api" }
application = { path = "../application" }
infra = { path = "../infra" }
tokio.workspace = true
