name: ci
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            cd backend
            cargo +nightly fmt -- --check
            cargo clippy -- --deny warnings
            cargo test
